import Head from 'next/head';
import { Box, Flex, Text } from '@chakra-ui/react';
import { getUserList } from '@/utils/firebase/users';
import { useEffect, useState } from 'react';
import { Link } from '@chakra-ui/next-js';

export default function Home() {
  const [users, setUsers] = useState([]);
  const fetchUser = async () => {
    const data = await getUserList();
    setUsers(data);
  };

  useEffect(() => {
    fetchUser();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        direction="column"
        alignItems="center"
        gap="16px"
        px="30px"
        py="30px"
      >
        <Text>Choose your user:</Text>
        {users.map((user) => (
          <Link key={user.id} href={`/users/${user.id}/chats`}>
            <Box
              border="1px solid black"
              borderRadius="10px"
              padding="5px"
            >
              <Text>id: {user.id}</Text>
              <Text>username: {user.username}</Text>
            </Box>
          </Link>
        ))}
      </Flex>
    </>
  );
}
